import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@components/ui/sonner';
import { cn } from '@lib/cn';

const fontHeading = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-heading',
});

const fontBody = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-body',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={cn('antialiased', fontHeading.variable, fontBody.variable)}
			>
				{children}
				<Toaster richColors theme='light' />
			</body>
		</html>
	);
}
